version: '3.8'

services:
  moyeo-mysql:
    image: mysql:8
    container_name: moyeo-mysql
    ports:
      - 13308:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
    volumes:
      - ./db/mysql:/var/lib/mysql
  moyeo-redis:
    image: redis:alpine
    container_name: moyeo-redis
    ports:
      - 16381:6379
    restart: on-failure
  moyeo-auth:
    container_name: moyeo-auth
    build: .
    ports:
      - 8081:8080
    env_file:
      - .env
    depends_on:
      - moyeo-mysql
      - moyeo-redis
  moyeo-opensearch1:
    restart: always
    build:
      context: ${ADMIN_PATH}/opensearch
      args:
        OPENSEARCH_VERSION: ${OPENSEARCH_VERSION}
    container_name: moyeo-opensearch1
    environment:
      cluster.name: moyeo-cluster
      node.name: moyeo-opensearch1
      discovery.seed_hosts: moyeo-opensearch1
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      DISABLE_SECURITY_PLUGIN: "true"
      discovery.type: single-node
      TZ: Asia/Seoul
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600  
volumes:
  opensearch-data: