version: '3.8'

services:
  moyeo-mysql:
    image: mysql:8
    container_name: moyeo-mysql
    ports:
      - 13308:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - moyeo-network
  moyeo-redis:
    image: redis:alpine
    container_name: moyeo-redis
    ports:
      - 16381:6379
    restart: on-failure
    networks:
      - moyeo-network
  moyeo-auth:
    container_name: moyeo-auth
    build: .
    ports:
      - 8081:8080
    volumes:
      - moyeo-auth-data:${AUTH_DATA_PATH}:rw,Z
    env_file:
      - .env
    depends_on:
      - moyeo-mysql
      - moyeo-redis
    networks:
      - moyeo-network
  moyeo-filebeat:
    build:
      context: ${ADMIN_PATH}/filebeat
      args:
        FILEBEAT_VERSION: ${FILEBEAT_VERSION}
    # windows DACL
    entrypoint: "filebeat -e -strict.perms=false"
    environment:
      AUTH_DATA_PATH: ${AUTH_DATA_PATH}
      LOGSTASH_URL: ${LOGSTASH_URL}
    volumes:
      - ${ADMIN_PATH}/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:rw,Z
      - filebeat-data:/usr/share/filebeat
      - moyeo-auth-data:${AUTH_DATA_PATH}:rw,Z
    networks:
      - moyeo-network
volumes:
  filebeat-data:
  moyeo-auth-data:
networks: 
  moyeo-network:
    external: false
    name: moyeo-network