version: '3.8'

services:
  moyeo-opensearch1:
    restart: always
    build:
      context: ${ADMIN_PATH}/opensearch
      args:
        OPENSEARCH_VERSION: ${OPENSEARCH_VERSION}
    container_name: moyeo-opensearch1
    environment:
      cluster.name: moyeo-cluster
      node.name: moyeo-opensearch1
      discovery.seed_hosts: moyeo-opensearch1
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      DISABLE_SECURITY_PLUGIN: "true"
      discovery.type: single-node
      TZ: Asia/Seoul
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - moyeo-monitor-network
  moyeo-opensearch-dashboards:
    restart: always
    build:
      context: ${ADMIN_PATH}/opensearch-dashboards
      args:
        OPENSEARCH_VERSION: ${OPENSEARCH_VERSION}
    container_name: moyeo-opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      OPENSEARCH_HOSTS: '["http://moyeo-opensearch1:9200"]'
    depends_on:
      - moyeo-opensearch1
    networks:
      - moyeo-monitor-network
  moyeo-logstash:
    build:
      context: ${ADMIN_PATH}/logstash
      args: 
        LOGSTASH_VERSION: ${LOGSTASH_VERSION}
    volumes:
      - ${ADMIN_PATH}/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ${ADMIN_PATH}/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - "5044:5044"
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: -Xmx1g -Xms1g
      TZ: Asia/Seoul
      OPENSEARCH_URL: ${OPENSEARCH_URL}
    depends_on:
      - moyeo-opensearch1
    networks:
      - moyeo-monitor-network
volumes:
  opensearch-data:

networks:
  moyeo-monitor-network:
    external:
      name: moyeo-network